// UNDER DEVELOPMENT — v3: adds Assign ('='), Effect, and Speak for the
// wave-backend grammar extensions (effects chain, seeded humanize parameters,
// phoneme/prosody tone mapping). Pure additions — no existing token changed.
namespace SoundScript.Core;

public enum TokenType
{
    Melody,
    LeftBrace,
    RightBrace,
    Bpm,
    Tempo,
    Over,
    Bars,
    Arrow,
    Time,
    Play,
    For,
    Colon,
    Bar,
    Slash,
    Note,
    Chord,
    ChordVoicing,
    Number,
    Identifier,
    Instrument,
    Layer,
    Gain,
    Humanize,
    Sequence,
    Block,
    Loop,
    Velocity,
    Track,
    Duration,
    VelocityPrefix,
    Rest,
    Tie,
    Articulation,
    Dynamic,
    Phrase,
    Curve,
    Transition,
    PhraseArticulation,
    Crescendo,
    Decrescendo,
    Swing,
    Push,
    Pull,
    Pattern,
    PatternDirective,
    PatternRhythm,
    Orchestration,
    Import,
    StringLiteral,
    Voice,
    Sing,
    Vocal,
    // v3 (wave-motivated grammar; see SoundScript.Wave):
    Assign,     // '=' in key=value directive parameters
    Effect,     // 'effect' — master effects chain (wave backend only)
    Speak,      // 'speak' — phoneme/prosody tone mapping (wave backend only)
    EndOfFile
}
